"""Local monitor owns its public listener, temporary tunnel and durable read-only intake."""

from __future__ import annotations

import asyncio
import hashlib
import json
import re
import subprocess
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import TYPE_CHECKING, Any
from uuid import UUID

import httpx
import uvicorn
from sqlalchemy import select

from agentic_product_ops.adapters.linear.intake import repository_name
from agentic_product_ops.adapters.linear.monitor import (
    configure_webhook,
    pause_webhook,
    poll_events,
)
from agentic_product_ops.adapters.linear.native_graphql import NativeGraphQLAdapter
from agentic_product_ops.adapters.persistence.store import Missing, operations
from agentic_product_ops.api.linear_webhook import webhook_app
from agentic_product_ops.cli import bounded_read
from agentic_product_ops.pilot.config import secret_from_env
from agentic_product_ops.policies.validation import PolicyError
from agentic_product_ops.services.linear_events import LinearEvent, LinearInbox

if TYPE_CHECKING:
    from agentic_product_ops.pilot.runtime import PilotRuntime


class LinearMonitor:
    def __init__(self, runtime: PilotRuntime):
        self.runtime = runtime
        self.inbox = LinearInbox(runtime.store, runtime.settings.workspace)
        self.secrets = json.loads(bounded_read(runtime.directory / "monitor-secrets.json", 4096))
        if (
            set(self.secrets) != {"webhook_id", "webhook_secret"}
            or len(self.secrets["webhook_secret"]) < 32
        ):
            raise ValueError("invalid monitor secrets")
        self.webhook_id = UUID(self.secrets["webhook_id"])

    def adapter(self, *, manage: bool = False) -> NativeGraphQLAdapter:
        settings = self.runtime.settings
        return NativeGraphQLAdapter(
            settings.linear_scope,
            token=secret_from_env(Path(settings.linear_key_file), "LINEAR_API_KEY"),
            token_kind="api_key",  # noqa: S106
            # Only the explicit webhook-management adapter declares a write-capable scope.
            scopes=("read", "admin") if manage else ("read",),
            allow_network=True,
            allow_mutations=manage,
        )

    def reconcile(self, now: datetime) -> int:
        enrolled = self.runtime.settings.linear_monitor_enrolled_at
        if enrolled is None:
            raise PolicyError("monitor enrollment required")
        since = max(enrolled, self.inbox.cursor(enrolled) - timedelta(minutes=2))
        adapter = self.adapter()
        try:
            events = poll_events(adapter, since, now, enrolled)
        finally:
            adapter.close()
        # Cursor advances only after the entire bounded result set is durably accepted.
        for event in events:
            self.inbox.receive(event)
        self.inbox.advance(now)
        return len(events)

    def process(self, event: LinearEvent) -> None:
        runtime, settings = self.runtime, self.runtime.settings
        enrolled = settings.linear_monitor_enrolled_at
        if enrolled is None or event.created_at < enrolled:
            self.inbox.finish(event, "EXCLUDED_PRE_ENROLLMENT")
            return
        if event.action == "remove":
            self.inbox.finish(event, "SOURCE_REMOVED")
            return
        with runtime.store.database.connect() as conn:
            generated = conn.execute(
                select(operations.c.operation_key)
                .where(
                    operations.c.workspace == settings.workspace,
                    operations.c.provider_id == str(event.issue_id),
                )
                .limit(1)
            ).first()
        if generated:
            self.inbox.finish(event, "EXCLUDED_GENERATED")
            return
        source = runtime.read_linear_source(str(event.issue_id))
        if source.created_at is None or source.created_at < enrolled:
            self.inbox.finish(event, "EXCLUDED_PRE_ENROLLMENT")
            return
        if "Generated by Agentic Product Ops" in source.description:
            self.inbox.finish(event, "EXCLUDED_GENERATED")
            return
        name = repository_name(source, None)
        # Steps 1-4 are a monitoring acceptance lane. Never implicitly launch paid work.
        if settings.allow_paid_execution or settings.allow_publication:
            raise PolicyError("monitor acceptance requires paid execution and publication disabled")
        with httpx.Client(
            base_url=f"http://127.0.0.1:{settings.api_port}",
            trust_env=False,
            follow_redirects=False,
            timeout=30,
        ) as client:
            response = client.post(
                "/v1/intakes/linear",
                json={"issue": str(event.issue_id), "repository": name},
                headers={"Authorization": "Bearer " + runtime.secrets["operator_token"]},
            )
        if response.status_code in {401, 403, 409, 422}:
            self.inbox.finish(event, "HELD", {"http_status": response.status_code})
        elif response.status_code == 201:
            result = response.json()
            if result.get("workflow") != "held_paid_execution_disabled":
                raise PolicyError("monitor intake execution boundary changed")
            self.inbox.finish(event, "INTAKE_HELD", result)
        else:
            raise RuntimeError("local intake temporarily unavailable")

    def consume(self, now: datetime) -> dict[str, int]:
        counts = {"processed": 0, "retrying": 0, "held": 0}
        for event in self.inbox.pending(20):
            try:
                attempt = self.runtime.store.get(
                    self.inbox.workspace, "linear_event_attempt", event.key()
                )
            except Missing:
                attempt = {"revision": 0, "retry_at": now.isoformat()}
            if datetime.fromisoformat(attempt["retry_at"]) > now:
                counts["retrying"] += 1
                continue
            try:
                self.process(event)
                counts["processed"] += 1
            except PolicyError:
                self.inbox.finish(event, "HELD_POLICY")
                counts["held"] += 1
            except Exception:
                revision = attempt["revision"] + 1
                if revision >= 10:
                    self.inbox.finish(event, "HELD_RETRY_EXHAUSTED")
                    counts["held"] += 1
                    continue
                delay = min(300, 2**revision)
                with self.runtime.store.database.begin() as conn:
                    self.runtime.store.put(
                        conn,
                        self.inbox.workspace,
                        "linear_event_attempt",
                        event.key(),
                        revision,
                        {
                            "revision": revision,
                            "retry_at": (now + timedelta(seconds=delay)).isoformat(),
                        },
                    )
                counts["retrying"] += 1
        return counts

    def register(self, url: str) -> dict[str, Any]:
        adapter = self.adapter(manage=True)
        try:
            return configure_webhook(
                adapter, self.webhook_id, url + "/webhooks/linear", self.secrets["webhook_secret"]
            )
        finally:
            adapter.close()

    def pause(self) -> dict[str, Any]:
        adapter = self.adapter(manage=True)
        try:
            return pause_webhook(adapter, self.webhook_id)
        finally:
            adapter.close()

    def report(self, status: dict[str, Any]) -> None:
        temporary = self.runtime.directory / "monitor-health.tmp"
        temporary.write_text(
            json.dumps({"at": datetime.now(UTC).isoformat(), **status}), encoding="utf-8"
        )
        temporary.replace(self.runtime.directory / "monitor-health.json")

    async def run(self) -> None:
        settings = self.runtime.settings
        executable = Path(settings.cloudflared_path or "")
        if hashlib.sha256(executable.read_bytes()).hexdigest() != settings.cloudflared_sha256:
            raise PolicyError("tunnel executable digest changed")
        app = webhook_app(
            self.inbox,
            self.secrets["webhook_secret"],
            settings.linear_scope.organization_id,
            {t.provider_id for t in settings.linear_scope.teams},
        )
        server = uvicorn.Server(
            uvicorn.Config(
                app,
                host="127.0.0.1",
                port=settings.linear_webhook_port,
                access_log=False,
                proxy_headers=False,
                limit_concurrency=16,
            )
        )
        task = asyncio.create_task(server.serve())
        tunnel = None
        log = self.runtime.directory / "tunnel.log"
        status: dict[str, Any] = {"mode": "acceptance_no_execution", "webhook_registered": False}
        next_poll = datetime.min.replace(tzinfo=UTC)
        next_registration = datetime.min.replace(tzinfo=UTC)
        try:
            while not server.started:
                if task.done():
                    task.result()
                    raise RuntimeError("webhook listener stopped")
                await asyncio.sleep(0.1)
            with log.open("w", encoding="utf-8") as stream:
                tunnel = subprocess.Popen(  # noqa: S603
                    [
                        str(executable),
                        "tunnel",
                        "--url",
                        f"http://127.0.0.1:{settings.linear_webhook_port}",
                        "--no-autoupdate",
                        "--protocol",
                        "http2",
                    ],
                    stdout=stream,
                    stderr=stream,
                    creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
                )
                (self.runtime.directory / "tunnel-process.json").write_text(
                    json.dumps(
                        {
                            "pid": tunnel.pid,
                            "executable": str(executable),
                            "port": settings.linear_webhook_port,
                        }
                    ),
                    encoding="utf-8",
                )
                url = None
                while True:
                    if tunnel.poll() is not None or task.done():
                        raise RuntimeError("public listener or tunnel stopped")
                    if url is None:
                        match = re.search(
                            r"https://[a-z0-9-]+\.trycloudflare\.com",
                            bounded_read(log, 2000000).decode("utf-8"),
                        )
                        if match:
                            url = match[0]
                    now = datetime.now(UTC)
                    if url and now >= next_registration:
                        try:
                            await asyncio.to_thread(self.register, url)
                            status.update(
                                webhook_registered=True, public_url=url + "/webhooks/linear"
                            )
                            status.pop("registration_error", None)
                            next_registration = now + timedelta(minutes=5)
                        except Exception:
                            status["webhook_registered"] = False
                            status["registration_error"] = "registration held; retrying owned ID"
                            next_registration = now + timedelta(minutes=1)
                    if now >= next_poll:
                        try:
                            status["reconciled_events"] = await asyncio.to_thread(
                                self.reconcile, now
                            )
                            status["last_poll_success"] = now.isoformat()
                            status.pop("poll_error", None)
                        except Exception:
                            status["poll_error"] = "reconciliation held; cursor preserved"
                        next_poll = now + timedelta(minutes=5)
                    try:
                        status.update(await asyncio.to_thread(self.consume, now))
                        status["last_received"] = self.inbox.latest("linear_event")
                        status["last_result"] = self.inbox.latest("linear_event_result")
                        pending = self.inbox.pending(100)
                        status["pending_bounded"] = len(pending)
                        status["oldest_pending_seconds"] = max(
                            (int((now - e.updated_at).total_seconds()) for e in pending), default=0
                        )
                    except Exception:
                        status["inbox_error"] = "inbox processing held"
                    self.report(status)
                    await asyncio.sleep(5)
        finally:
            # Pause delivery before the tunnel goes away, so Linear does not record failures and
            # disable the webhook. Best effort: a hard kill skips this, and `stop` covers that.
            try:
                await asyncio.to_thread(self.pause)
            except Exception:
                status["pause_error"] = "webhook pause held; run product-ops-pilot stop"
            if tunnel is not None:
                tunnel.terminate()
                try:
                    await asyncio.to_thread(tunnel.wait, 5)
                except subprocess.TimeoutExpired:
                    tunnel.kill()
                    await asyncio.to_thread(tunnel.wait)
            server.should_exit = True
            task.cancel()
            await asyncio.gather(task, return_exceptions=True)
            self.report({"stopped": True})
